### PR TITLE
update git release download url

### PR DESCRIPTION
**Pull request by iqianxing**
update git release download url

### CODE REVIEW

**Comment by sorccu** [comment]
Can you let me know why this change is required? Did GitHub change the URL?
Is there a blog post or something about this?

**Comment by iqianxing** [comment]
open the download url will return 404

**Comment by sorccu** [comment]
Is it possible you may not actually have created a release? A plain tag
probably isn't enough. I don't see any evidence of a URL change in the
GitHub docs.

**Comment by iqianxing** [comment]
@sorccu  Thank u!

**Pull request closed without merging**
